"""'AddDefaultValueInProgress'

Revision ID: 09af54dddfaf
Revises: 
Create Date: 2023-11-11 18:15:07.694072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09af54dddfaf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'module', ['module_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'module', type_='unique')
    # ### end Alembic commands ###
